// ============================================================================
// JOB APPLICANTS & RECRUITMENT DATA STORE (Module 12)
// Multi-tenant realistic data for Coaching Faculty & Academic Staff Hiring
// ============================================================================

export const MOCK_APPLICANTS = [
  {
    id: 'JOB-401',
    candidateName: 'Dr. Vivek Sengupta',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Head of Physical Sciences (IIT-JEE)',
    subject: 'Physics',
    specialization: 'Electrodynamics & Modern Physics',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    experience: '12 Yrs',
    qualification: 'Ph.D. Physics, Cambridge Univ',
    previousInstitutes: 'Allen Career Institute (Kota), FIITJEE South Delhi',
    stage: 'Demo Lecture Round',
    rating: 4.9,
    expectedCTC: '$92,000 / yr',
    currentCTC: '$78,000 / yr',
    noticePeriod: '15 Days',
    appliedDate: 'Sep 10, 2026',
    sourcingChannel: 'Faculty Referral',
    email: 'vivek.sengupta@academicmail.com',
    phone: '+1 (555) 392-1084',
    demoTopic: 'Electromagnetic Induction: Lenz Law & Eddy Current Energy Losses',
    demoDate: 'Today, 03:30 PM',
    demoRoom: 'Smart Studio B-2',
    demoScores: {
      conceptClarity: 5.0,
      pedagogyBoard: 4.8,
      examShortcuts: 4.9,
      dictionPresence: 4.8
    },
    demoStatus: 'Completed',
    demoVideoDuration: '18:42 min',
    evaluatorNotes: 'Exceptional conceptual depth. Solved advanced Irodov problems on smartboard with intuitive geometric vector diagrams. 98% student panel rating.',
    status: 'In Review'
  },
  {
    id: 'JOB-402',
    candidateName: 'Pooja Kashyap',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Senior Faculty - Organic Chemistry',
    subject: 'Chemistry',
    specialization: 'Reaction Mechanisms & Stereochemistry',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    experience: '8 Yrs',
    qualification: 'M.Sc. Organic Chemistry, Delhi University (Gold Medalist)',
    previousInstitutes: 'Aakash Educational Services, Resonance Kota',
    stage: 'Director Interview',
    rating: 4.7,
    expectedCTC: '$75,000 / yr',
    currentCTC: '$64,000 / yr',
    noticePeriod: 'Immediate Joiner',
    appliedDate: 'Sep 12, 2026',
    sourcingChannel: 'LinkedIn Talent',
    email: 'pooja.kashyap@chemprep.org',
    phone: '+1 (555) 441-2980',
    demoTopic: 'Nucleophilic Addition to Carbonyls & Grignard Reagent Synthesis',
    demoDate: 'Yesterday, 11:00 AM',
    demoRoom: 'Lecture Hall 4A',
    demoScores: {
      conceptClarity: 4.8,
      pedagogyBoard: 4.7,
      examShortcuts: 4.6,
      dictionPresence: 4.8
    },
    demoStatus: 'Completed',
    demoVideoDuration: '21:15 min',
    evaluatorNotes: 'Outstanding mnemonic tricks for memorizing reaction pathways. Highly structured chalkboard layout. Approved by HOD Chemistry.',
    status: 'Shortlisted'
  },
  {
    id: 'JOB-403',
    candidateName: 'Marcus Wright, FCA',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Faculty - Corporate Tax & Accounting',
    subject: 'Commerce & CA',
    specialization: 'CA Final Corporate Law & Direct Tax',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy & CA Foundation',
    experience: '10 Yrs',
    qualification: 'Fellow Chartered Accountant (FCA England & Wales)',
    previousInstitutes: 'Kaplan Financial London, PwC Learning Academy',
    stage: 'Offer Extended',
    rating: 4.9,
    expectedCTC: '$96,000 / yr',
    currentCTC: '$88,000 / yr',
    noticePeriod: '1 Month',
    appliedDate: 'Sep 05, 2026',
    sourcingChannel: 'Executive Search',
    email: 'marcus.wright@fcalondon.co.uk',
    phone: '+44 20 7946 0881',
    demoTopic: 'Transfer Pricing Adjustments & BEPS Multi-jurisdictional Compliance',
    demoDate: 'Sep 14, 2026',
    demoRoom: 'Executive Boardroom C',
    demoScores: {
      conceptClarity: 5.0,
      pedagogyBoard: 4.9,
      examShortcuts: 4.7,
      dictionPresence: 4.9
    },
    demoStatus: 'Completed',
    demoVideoDuration: '24:50 min',
    evaluatorNotes: 'Top-tier corporate practitioner. Case-study driven pedagogy. Offer letter released with joining date of Oct 1, 2026.',
    status: 'Offer Released'
  },
  {
    id: 'JOB-404',
    candidateName: 'Dr. Elena Vasquez',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    role: 'NEET Master Lead - Human Physiology',
    subject: 'Biology',
    specialization: 'Neurobiology & Endocrine Pathology',
    instituteCode: 'apex',
    instituteName: 'Apex Medical & Pre-Engineering Prep',
    experience: '7 Yrs',
    qualification: 'MD Physiology, Johns Hopkins University',
    previousInstitutes: 'Medical Academy Boston, Princeton Review Pre-Med',
    stage: 'Demo Lecture Round',
    rating: 4.8,
    expectedCTC: '$88,000 / yr',
    currentCTC: '$74,000 / yr',
    noticePeriod: '30 Days',
    appliedDate: 'Sep 14, 2026',
    sourcingChannel: 'LinkedIn Talent',
    email: 'elena.vasquez@hopkinsalumni.edu',
    phone: '+1 (555) 819-3320',
    demoTopic: 'Action Potential Generation in Myelinated Axons & Synaptic Transmission',
    demoDate: 'Tomorrow, 10:00 AM',
    demoRoom: 'Medical Lab Theater 1',
    demoScores: {
      conceptClarity: 4.9,
      pedagogyBoard: 4.8,
      examShortcuts: 4.7,
      dictionPresence: 4.9
    },
    demoStatus: 'Scheduled',
    demoVideoDuration: 'Pending Live',
    evaluatorNotes: 'High-yield diagrammatic explanations. High expectations from demo jury panel tomorrow.',
    status: 'Demo Scheduled'
  },
  {
    id: 'JOB-405',
    candidateName: 'Karan Malhotra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Senior Faculty - Pure Mathematics',
    subject: 'Mathematics',
    specialization: 'Integral Calculus & Coordinate Geometry',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    experience: '9 Yrs',
    qualification: 'B.Tech + M.Tech Mathematics & Computing, IIT Kanpur',
    previousInstitutes: 'Chaitanya Educational Group, Narayana IIT Academy',
    stage: 'Sourced & Screening',
    rating: 4.5,
    expectedCTC: '$82,000 / yr',
    currentCTC: '$70,000 / yr',
    noticePeriod: '15 Days',
    appliedDate: 'Sep 17, 2026',
    sourcingChannel: 'Direct Website',
    email: 'karan.malhotra@iitkalum.in',
    phone: '+1 (555) 723-9011',
    demoTopic: 'Definite Integration using King & Queen Properties in JEE Advanced',
    demoDate: 'Sep 21, 2026',
    demoRoom: 'Studio A-1',
    demoScores: {
      conceptClarity: 4.6,
      pedagogyBoard: 4.5,
      examShortcuts: 4.8,
      dictionPresence: 4.4
    },
    demoStatus: 'Pending',
    demoVideoDuration: 'Not Recorded',
    evaluatorNotes: 'Resume shortlisted based on IIT Kanpur credentials and 9 years track record producing top 100 AIRs.',
    status: 'Resume Screened'
  },
  {
    id: 'JOB-406',
    candidateName: 'Aishwarya Raman',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'Educator - Botany & Cell Biology',
    subject: 'Biology',
    specialization: 'Plant Genetics & Photosynthetic Pathways',
    instituteCode: 'apex',
    instituteName: 'Apex Medical & Pre-Engineering Prep',
    experience: '5 Yrs',
    qualification: 'M.Sc. Botany, Univ of Madras (Gold Medalist)',
    previousInstitutes: 'Narayana Medical Academy, Speed Medical Institute',
    stage: 'Written Test',
    rating: 4.6,
    expectedCTC: '$62,000 / yr',
    currentCTC: '$52,000 / yr',
    noticePeriod: 'Immediate',
    appliedDate: 'Sep 15, 2026',
    sourcingChannel: 'Faculty Referral',
    email: 'aishwarya.raman@botanylead.in',
    phone: '+1 (555) 902-3114',
    demoTopic: 'Calvin Cycle & C4 dicarboxylic acid pathway enzyme regulation',
    demoDate: 'Sep 22, 2026',
    demoRoom: 'Lab Studio 3',
    demoScores: {
      conceptClarity: 4.7,
      pedagogyBoard: 4.6,
      examShortcuts: 4.5,
      dictionPresence: 4.6
    },
    demoStatus: 'Pending',
    demoVideoDuration: 'Not Recorded',
    evaluatorNotes: 'Scored 96/100 on internal faculty subject proficiency assessment. Scheduled for demo next Tuesday.',
    status: 'Written Test Cleared'
  },
  {
    id: 'JOB-407',
    candidateName: 'David H. Miller',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'Instructor - AI & Algorithmic Problem Solving',
    subject: 'Computer Science',
    specialization: 'Data Structures & Competitive Programming',
    instituteCode: 'delta',
    instituteName: 'Delta Coding Academy & AI Scholars',
    experience: '6 Yrs',
    qualification: 'M.S. Computer Science, UC Berkeley',
    previousInstitutes: 'General Assembly San Francisco, Hack Reactor',
    stage: 'Joined & Onboarded',
    rating: 4.9,
    expectedCTC: '$105,000 / yr',
    currentCTC: '$95,000 / yr',
    noticePeriod: 'Joined Sep 01',
    appliedDate: 'Aug 20, 2026',
    sourcingChannel: 'LinkedIn Talent',
    email: 'david.miller@berkeleycs.edu',
    phone: '+1 (555) 612-4098',
    demoTopic: 'Dynamic Programming on Trees & Graph Vertex Cover Reductions',
    demoDate: 'Aug 28, 2026',
    demoRoom: 'Main Lab A',
    demoScores: {
      conceptClarity: 5.0,
      pedagogyBoard: 4.9,
      examShortcuts: 4.9,
      dictionPresence: 4.8
    },
    demoStatus: 'Completed',
    demoVideoDuration: '22:10 min',
    evaluatorNotes: 'Officially joined on Sep 1, 2026. Allocated to Advanced Coding Cohort 3 & 4.',
    status: 'Onboarded'
  },
  {
    id: 'JOB-408',
    candidateName: 'Adv. Meenakshi Sundaram',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'Professor - Constitutional Law & Jurisprudence',
    subject: 'Humanities & Law',
    specialization: 'CLAT UG/PG Legal Reasoning & Moot Court',
    instituteCode: 'zenith',
    instituteName: 'Zenith Humanities & Law Foundation',
    experience: '11 Yrs',
    qualification: 'LL.M. Harvard Law School, Advocate High Court',
    previousInstitutes: 'Career Launcher LST, Clat Possible',
    stage: 'Director Interview',
    rating: 4.8,
    expectedCTC: '$88,000 / yr',
    currentCTC: '$75,000 / yr',
    noticePeriod: '30 Days',
    appliedDate: 'Sep 08, 2026',
    sourcingChannel: 'Faculty Referral',
    email: 'meenakshi.s@harvardalumni.law',
    phone: '+1 (555) 438-7712',
    demoTopic: 'Basic Structure Doctrine: Kesavananda Bharati to Judicial Primacy',
    demoDate: 'Sep 16, 2026',
    demoRoom: 'Moot Court Room Z',
    demoScores: {
      conceptClarity: 4.9,
      pedagogyBoard: 4.8,
      examShortcuts: 4.7,
      dictionPresence: 5.0
    },
    demoStatus: 'Completed',
    demoVideoDuration: '25:30 min',
    evaluatorNotes: 'Stunning oratorical presence and case law mastery. Director interview in progress for lead faculty appointment.',
    status: 'Director Round'
  },
  {
    id: 'JOB-409',
    candidateName: 'Rahul Sachdeva',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    role: 'Faculty - Physical Chemistry & Thermodynamics',
    subject: 'Chemistry',
    specialization: 'Chemical Kinetics & Electrochemistry',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    experience: '6 Yrs',
    qualification: 'M.Sc. Chemistry, IIT Roorkee',
    previousInstitutes: 'Bansal Classes Kota, Career Point',
    stage: 'Written Test',
    rating: 4.4,
    expectedCTC: '$68,000 / yr',
    currentCTC: '$58,000 / yr',
    noticePeriod: '30 Days',
    appliedDate: 'Sep 16, 2026',
    sourcingChannel: 'Indeed Portal',
    email: 'rahul.sachdeva@iitrchem.in',
    phone: '+1 (555) 209-8812',
    demoTopic: 'Gibbs Free Energy & Non-Equilibrium Cell Potentials',
    demoDate: 'Sep 24, 2026',
    demoRoom: 'Studio B-1',
    demoScores: {
      conceptClarity: 4.5,
      pedagogyBoard: 4.4,
      examShortcuts: 4.3,
      dictionPresence: 4.4
    },
    demoStatus: 'Pending',
    demoVideoDuration: 'Not Recorded',
    evaluatorNotes: 'Passed technical written screening. Written test score: 88/100.',
    status: 'Written Test Passed'
  },
  {
    id: 'JOB-410',
    candidateName: 'Dr. Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    role: 'Faculty - Advanced Macroeconomics & Quant',
    subject: 'Commerce & CA',
    specialization: 'Monetary Economics & Financial Markets',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy & CA Foundation',
    experience: '8 Yrs',
    qualification: 'Ph.D. Economics, London School of Economics',
    previousInstitutes: 'BPP University London, City University',
    stage: 'Offer Extended',
    rating: 4.8,
    expectedCTC: '$84,000 / yr',
    currentCTC: '$75,000 / yr',
    noticePeriod: '15 Days',
    appliedDate: 'Sep 06, 2026',
    sourcingChannel: 'LinkedIn Talent',
    email: 's.jenkins@lsealumni.org.uk',
    phone: '+44 20 7946 0419',
    demoTopic: 'IS-LM-BP Open Economy Model under Floating vs Fixed Exchange Rates',
    demoDate: 'Sep 12, 2026',
    demoRoom: 'Room L-201',
    demoScores: {
      conceptClarity: 4.9,
      pedagogyBoard: 4.7,
      examShortcuts: 4.8,
      dictionPresence: 4.8
    },
    demoStatus: 'Completed',
    demoVideoDuration: '20:15 min',
    evaluatorNotes: 'Contract sent. Expected to join first week of October to take over CA Foundation Economics batches.',
    status: 'Offer Pending Signature'
  }
];

// Open positions vs filled per department
export const REQUISITIONS_DATA = [
  { department: 'Physics (IIT-JEE / NEET)', openPositions: 4, filledPositions: 3, urgency: 'Critical', avgSalary: '$85,000' },
  { department: 'Chemistry (Organic & Physical)', openPositions: 3, filledPositions: 2, urgency: 'High', avgSalary: '$78,000' },
  { department: 'Mathematics (Advanced Calculus)', openPositions: 4, filledPositions: 4, urgency: 'Filled', avgSalary: '$82,000' },
  { department: 'Biology & Medical Science', openPositions: 3, filledPositions: 1, urgency: 'Critical', avgSalary: '$75,000' },
  { department: 'Commerce, CA & Corporate Law', openPositions: 3, filledPositions: 2, urgency: 'Medium', avgSalary: '$90,000' },
  { department: 'Computer Science & AI', openPositions: 2, filledPositions: 1, urgency: 'Medium', avgSalary: '$98,000' }
];

// Recruitment sourcing channel ROI analytics
export const CHANNEL_ROI_DATA = [
  {
    channel: 'Faculty & Staff Referrals',
    applicants: 38,
    screened: 29,
    demoGiven: 18,
    offersAccepted: 6,
    conversionRate: '15.8%',
    costPerHire: '$140',
    retentionRate1Yr: '96.4%',
    qualityRating: 4.88,
    badge: 'Best Retention & ROI'
  },
  {
    channel: 'LinkedIn Talent Solutions',
    applicants: 72,
    screened: 32,
    demoGiven: 14,
    offersAccepted: 4,
    conversionRate: '5.5%',
    costPerHire: '$520',
    retentionRate1Yr: '89.0%',
    qualityRating: 4.75,
    badge: 'Highest Volume'
  },
  {
    channel: 'Alumni Network & Academics',
    applicants: 24,
    screened: 18,
    demoGiven: 11,
    offersAccepted: 3,
    conversionRate: '12.5%',
    costPerHire: '$80',
    retentionRate1Yr: '94.2%',
    qualityRating: 4.82,
    badge: 'Lowest Cost'
  },
  {
    channel: 'Executive Search / Headhunters',
    applicants: 15,
    screened: 14,
    demoGiven: 9,
    offersAccepted: 3,
    conversionRate: '20.0%',
    costPerHire: '$1,450',
    retentionRate1Yr: '91.5%',
    qualityRating: 4.92,
    badge: 'Premium Senior HODs'
  },
  {
    channel: 'Direct Career Website Portal',
    applicants: 54,
    screened: 16,
    demoGiven: 6,
    offersAccepted: 2,
    conversionRate: '3.7%',
    costPerHire: '$60',
    retentionRate1Yr: '81.4%',
    qualityRating: 4.40,
    badge: 'Inbound Organic'
  }
];

// Stage velocity and funnel drop-off metrics
export const FUNNEL_VELOCITY_DATA = {
  stages: [
    { name: '1. Applications Received', count: 203, dropOffPct: '0%', avgDaysInStage: 1.4, color: 'bg-blue-500' },
    { name: '2. Resume & KYC Screened', count: 109, dropOffPct: '46.3%', avgDaysInStage: 2.1, color: 'bg-indigo-500' },
    { name: '3. Written Technical Exam', count: 58, dropOffPct: '46.7%', avgDaysInStage: 2.8, color: 'bg-cyan-500' },
    { name: '4. Live Teaching Demo Round', count: 32, dropOffPct: '44.8%', avgDaysInStage: 2.3, color: 'bg-emerald-500' },
    { name: '5. Director / HOD Round', count: 19, dropOffPct: '40.6%', avgDaysInStage: 3.1, color: 'bg-amber-500' },
    { name: '6. Offer Released & Joined', count: 18, dropOffPct: '5.2%', avgDaysInStage: 4.2, color: 'bg-purple-600' },
  ],
  campusVelocityComparison: [
    { campus: 'Alpha Institute (Tech & JEE)', avgDaysToHire: '13.8 Days', target: '18 Days', offersAccepted: 8, status: 'Fast Track' },
    { campus: 'Beta Commerce Academy (CA)', avgDaysToHire: '15.2 Days', target: '20 Days', offersAccepted: 4, status: 'On Target' },
    { campus: 'Apex Medical Prep (NEET)', avgDaysToHire: '14.1 Days', target: '18 Days', offersAccepted: 5, status: 'Fast Track' },
    { campus: 'Delta Coding Academy (AI)', avgDaysToHire: '12.4 Days', target: '15 Days', offersAccepted: 2, status: 'Optimal' },
    { campus: 'Zenith Humanities & Law', avgDaysToHire: '17.0 Days', target: '20 Days', offersAccepted: 2, status: 'Normal' },
  ]
};
