// Extended multi-branch faculty dataset enriched with attendance, leaves, payroll deductions, qualifications, and student app ratings
export const FACULTY_PAYROLL_DATA = [
  // ALPHA INSTITUTE (KOTA / MANHATTAN)
  {
    id: "FAC-01",
    name: "Dr. Harrison Wells",
    designation: "HOD & Senior Master Faculty",
    department: "Physics & Mechanics",
    instituteCode: "alpha",
    instituteName: "Alpha Institute of Science & Tech",
    campusCity: "Kota Campus (Main)",
    email: "harrison.wells@alphainstitute.edu",
    phone: "+91 98112 33451",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. Quantum Physics (MIT), M.Sc. IIT Kanpur",
    experienceYears: 14,
    joiningDate: "Aug 15, 2018",
    activeBatches: ["JEE Advanced Pinnacle", "Super-30 Star Batch", "Olympiad Level-2"],
    batchCount: 3,
    weeklyTeachingHours: 26,
    maxCapacityHours: 28,
    utilizationRate: 92.8,
    costPerStudentMonthly: 14.20,
    attendanceRate: 92.5,
    punctualityStreak: "11 Days",
    totalHoursLogged: 142.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 3,
    leavesLeft: 0,
    excessLeaves: 1, // LWP Day
    monthlySalary: 9500,
    perDayRate: 365.38,
    attendanceSalaryDeduction: 365.38,
    tdsDeduction: 913.46,
    performanceBonus: 450.00,
    netSalary: 8671.16,
    disbursalStatus: "Pending Approval",
    bankAccount: "HDFC •••• 8491",
    ifscCode: "HDFC0001822",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 03, 2026", type: "Casual Leave", days: 1, reason: "IIT Delhi Physics Colloquium Keynote", status: "Approved by Academic Director", isLWP: false, deduction: 0 },
      { date: "Sep 11, 2026", type: "Medical Leave", days: 1, reason: "Severe Migraine & Viral Flu", status: "Approved with Medical Certificate", isLWP: false, deduction: 0 },
      { date: "Sep 18, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "Personal Out-of-station Travel without Notice", status: "Salary Deduction Enforced (-$365.38)", isLWP: true, deduction: 365.38 }
    ],
    ratings: {
      overall: 4.92,
      totalReviews: 1840,
      fiveStarPercent: 94,
      conceptClarity: 98,
      punctualityScore: 92,
      doubtSolving: 97,
      examReadiness: 96,
      sentiment: "Outstanding",
      recentReviews: [
        { student: "Aarav Sharma", batch: "JEE Advanced Pinnacle", rating: 5, date: "Sep 15, 2026", comment: "Dr. Wells' Rotational Mechanics visual diagrams made the hardest Irodov problems seem intuitive and easy!" }
      ]
    }
  },
  {
    id: "FAC-02",
    name: "Prof. Ananya Roy",
    designation: "Lead Educator & Master Chemist",
    department: "Organic & Physical Chemistry",
    instituteCode: "alpha",
    instituteName: "Alpha Institute of Science & Tech",
    campusCity: "Kota Campus (Main)",
    email: "ananya.roy@alphainstitute.edu",
    phone: "+91 98223 44102",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. IIT Bombay, M.Sc. Chemistry Gold Medalist",
    experienceYears: 11,
    joiningDate: "Jul 01, 2020",
    activeBatches: ["NEET Super-60 Batch A", "Alpha Repeaters Star", "Class 12 Foundation"],
    batchCount: 3,
    weeklyTeachingHours: 24,
    maxCapacityHours: 26,
    utilizationRate: 92.3,
    costPerStudentMonthly: 12.80,
    attendanceRate: 98.0,
    punctualityStreak: "22 Days",
    totalHoursLogged: 156.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8200,
    perDayRate: 315.38,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 820.00,
    performanceBonus: 350.00,
    netSalary: 7730.00,
    disbursalStatus: "Disbursed",
    bankAccount: "ICICI •••• 4120",
    ifscCode: "ICIC0000491",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 07, 2026", type: "Casual Leave", days: 1, reason: "Family Religious Function", status: "Approved by Academic Director", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.88,
      totalReviews: 1420,
      fiveStarPercent: 91,
      conceptClarity: 96,
      punctualityScore: 99,
      doubtSolving: 95,
      examReadiness: 94,
      sentiment: "Exemplary",
      recentReviews: [
        { student: "Ananya Deshmukh", batch: "NEET Super-60 Batch A", rating: 5, date: "Sep 14, 2026", comment: "Reaction mechanisms and IUPAC nomenclature become crystal clear with Prof. Roy's handwritten mnemonics." }
      ]
    }
  },
  {
    id: "FAC-09",
    name: "Dr. Vikramaditya Sen",
    designation: "Senior Faculty Pure Mathematics",
    department: "Higher Calculus & Vectors",
    instituteCode: "alpha",
    instituteName: "Alpha Institute of Science & Tech",
    campusCity: "Kota Campus (Main)",
    email: "vikram.sen@alphainstitute.edu",
    phone: "+91 98441 90211",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. Mathematics (ISI Kolkata), B.Stat",
    experienceYears: 15,
    joiningDate: "Jan 12, 2017",
    activeBatches: ["JEE Advanced Pinnacle", "Calculus Masters"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.6,
    costPerStudentMonthly: 13.50,
    attendanceRate: 96.0,
    punctualityStreak: "19 Days",
    totalHoursLogged: 150.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8900,
    perDayRate: 342.30,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 890.00,
    performanceBonus: 400.00,
    netSalary: 8410.00,
    disbursalStatus: "Disbursed",
    bankAccount: "SBI •••• 6612",
    ifscCode: "SBIN0001099",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 12, 2026", type: "Casual Leave", days: 1, reason: "Attending Indian Mathematical Society Panel", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.90,
      totalReviews: 1580,
      fiveStarPercent: 93,
      conceptClarity: 99,
      punctualityScore: 97,
      doubtSolving: 96,
      examReadiness: 98,
      sentiment: "Master Mathematician",
      recentReviews: [
        { student: "Devansh V.", batch: "Calculus Masters", rating: 5, date: "Sep 16, 2026", comment: "Differential equations and contour integration simplified into pure visual logic!" }
      ]
    }
  },
  {
    id: "FAC-10",
    name: "Dr. Meenakshi Sundaram",
    designation: "Lead Educator Botanics & Zoology",
    department: "Cell Biology & Genetics",
    instituteCode: "alpha",
    instituteName: "Alpha Institute of Science & Tech",
    campusCity: "Kota Campus (Main)",
    email: "meenakshi.s@alphainstitute.edu",
    phone: "+91 97221 44588",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. Genetics (IISc Bangalore), M.Sc. Botany",
    experienceYears: 10,
    joiningDate: "Feb 01, 2021",
    activeBatches: ["NEET Super-60 Batch A", "Olympiad Bio Squad"],
    batchCount: 2,
    weeklyTeachingHours: 20,
    maxCapacityHours: 22,
    utilizationRate: 90.9,
    costPerStudentMonthly: 11.80,
    attendanceRate: 94.0,
    punctualityStreak: "14 Days",
    totalHoursLogged: 144.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 2,
    leavesLeft: 0,
    excessLeaves: 0,
    monthlySalary: 7800,
    perDayRate: 300.00,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 780.00,
    performanceBonus: 300.00,
    netSalary: 7320.00,
    disbursalStatus: "Disbursed",
    bankAccount: "Axis •••• 1928",
    ifscCode: "UTIB0000881",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 05, 2026", type: "Sick Leave", days: 1, reason: "Viral fever", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 19, 2026", type: "Casual Leave", days: 1, reason: "Family event", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.86,
      totalReviews: 1120,
      fiveStarPercent: 89,
      conceptClarity: 97,
      punctualityScore: 95,
      doubtSolving: 94,
      examReadiness: 96,
      sentiment: "Engaging and Supportive",
      recentReviews: [
        { student: "Ritu S.", batch: "NEET Super-60 Batch A", rating: 5, date: "Sep 18, 2026", comment: "Genetics Punnett squares are so easy now. Highly recommended!" }
      ]
    }
  },

  // BETA COMMERCE ACADEMY (MUMBAI / LONDON)
  {
    id: "FAC-03",
    name: "Er. Vivek Sharma",
    designation: "HOD Mathematics & Quantitative Aptitude",
    department: "Higher Calculus & Algebra",
    instituteCode: "beta",
    instituteName: "Beta Commerce Academy & CA Foundation",
    campusCity: "South Mumbai Center",
    email: "vivek.sharma@betainstitute.org",
    phone: "+91 98334 55219",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&auto=format&fit=crop&q=80",
    qualifications: "B.Tech Computer Science (IIT Delhi), M.Sc. Applied Math",
    experienceYears: 12,
    joiningDate: "Jan 10, 2019",
    activeBatches: ["CA Foundation Quant", "IIT JEE Math Mastery", "Calculus Pro"],
    batchCount: 3,
    weeklyTeachingHours: 25,
    maxCapacityHours: 28,
    utilizationRate: 89.3,
    costPerStudentMonthly: 15.50,
    attendanceRate: 88.0,
    punctualityStreak: "6 Days",
    totalHoursLogged: 136.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 4,
    leavesLeft: 0,
    excessLeaves: 2, // 2 LWP Days
    monthlySalary: 8800,
    perDayRate: 338.46,
    attendanceSalaryDeduction: 676.92,
    tdsDeduction: 812.31,
    performanceBonus: 200.00,
    netSalary: 7510.77,
    disbursalStatus: "Pending Approval",
    bankAccount: "Axis •••• 9923",
    ifscCode: "UTIB0000124",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 02, 2026", type: "Sick Leave", days: 1, reason: "Stomach Infection", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 09, 2026", type: "Casual Leave", days: 1, reason: "Personal Banking & Legal work", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 15, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "Unnotified absence on Tuesday mock lecture", status: "Salary Deduction Enforced (-$338.46)", isLWP: true, deduction: 338.46 },
      { date: "Sep 22, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "Extended weekend absent without reliever arranged", status: "Salary Deduction Enforced (-$338.46)", isLWP: true, deduction: 338.46 }
    ],
    ratings: {
      overall: 4.82,
      totalReviews: 1210,
      fiveStarPercent: 88,
      conceptClarity: 97,
      punctualityScore: 84,
      doubtSolving: 92,
      examReadiness: 95,
      sentiment: "High Quality (Needs Punctuality Focus)",
      recentReviews: [
        { student: "Emily Watson", batch: "CA Foundation Quant", rating: 4.5, date: "Sep 16, 2026", comment: "Superb shortcuts for probability and integration, but class was rescheduled twice this month." }
      ]
    }
  },
  {
    id: "FAC-08",
    name: "Adv. David Ross",
    designation: "Senior Faculty & Legal Counsel",
    department: "Corporate & Mercantile Law",
    instituteCode: "beta",
    instituteName: "Beta Commerce Academy & CA Foundation",
    campusCity: "South Mumbai Center",
    email: "david.ross@betainstitute.org",
    phone: "+91 98210 65432",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=160&auto=format&fit=crop&q=80",
    qualifications: "LL.M. Harvard Law School, Advocate High Court of Bombay",
    experienceYears: 17,
    joiningDate: "Aug 01, 2017",
    activeBatches: ["CA Inter Corporate Law", "CLAT Legal Reasoning"],
    batchCount: 2,
    weeklyTeachingHours: 20,
    maxCapacityHours: 22,
    utilizationRate: 90.9,
    costPerStudentMonthly: 14.50,
    attendanceRate: 94.0,
    punctualityStreak: "14 Days",
    totalHoursLogged: 145.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 2,
    leavesLeft: 0,
    excessLeaves: 0,
    monthlySalary: 8700,
    perDayRate: 334.62,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 870.00,
    performanceBonus: 350.00,
    netSalary: 8180.00,
    disbursalStatus: "Disbursed",
    bankAccount: "SBI •••• 9014",
    ifscCode: "SBIN0000452",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 05, 2026", type: "Casual Leave", days: 1, reason: "Supreme Court Special Hearing", status: "Approved by Director", isLWP: false, deduction: 0 },
      { date: "Sep 19, 2026", type: "Casual Leave", days: 1, reason: "Bar Council Meeting", status: "Approved by Director", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.87,
      totalReviews: 1340,
      fiveStarPercent: 90,
      conceptClarity: 96,
      punctualityScore: 94,
      doubtSolving: 96,
      examReadiness: 97,
      sentiment: "Master of Case Law",
      recentReviews: [
        { student: "Pooja Hegde", batch: "CA Inter Corporate Law", rating: 5, date: "Sep 14, 2026", comment: "Adv. Ross breaks down the Companies Act sections with real court examples. Unbeatable clarity!" }
      ]
    }
  },
  {
    id: "FAC-11",
    name: "Pooja Singhal, FCA",
    designation: "Lead Faculty Financial Reporting",
    department: "Advanced Auditing & Ind AS",
    instituteCode: "beta",
    instituteName: "Beta Commerce Academy & CA Foundation",
    campusCity: "South Mumbai Center",
    email: "pooja.singhal@betainstitute.org",
    phone: "+91 98200 11928",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80",
    qualifications: "FCA Rankholder 4, B.Com Gold Medalist",
    experienceYears: 13,
    joiningDate: "May 10, 2020",
    activeBatches: ["CA Final Ind AS Mastery", "Audit Star Regular"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.7,
    costPerStudentMonthly: 13.90,
    attendanceRate: 96.5,
    punctualityStreak: "18 Days",
    totalHoursLogged: 152.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8400,
    perDayRate: 323.08,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 840.00,
    performanceBonus: 300.00,
    netSalary: 7860.00,
    disbursalStatus: "Disbursed",
    bankAccount: "HDFC •••• 9921",
    ifscCode: "HDFC0000042",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 14, 2026", type: "Casual Leave", days: 1, reason: "ICAI Seminar Keynote", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.89,
      totalReviews: 1290,
      fiveStarPercent: 92,
      conceptClarity: 98,
      punctualityScore: 96,
      doubtSolving: 97,
      examReadiness: 98,
      sentiment: "Exceptional Clarity",
      recentReviews: [
        { student: "Karan Johar", batch: "CA Final Ind AS Mastery", rating: 5, date: "Sep 16, 2026", comment: "Ind AS 115 and Ind AS 116 consolidation made so simple with real balance sheets." }
      ]
    }
  },
  {
    id: "FAC-12",
    name: "Rajesh Kothari, CS",
    designation: "Faculty Economic Laws",
    department: "Securities & SEBI Regulations",
    instituteCode: "beta",
    instituteName: "Beta Commerce Academy & CA Foundation",
    campusCity: "South Mumbai Center",
    email: "rajesh.kothari@betainstitute.org",
    phone: "+91 98199 55301",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80",
    qualifications: "FCS, LL.B. Government Law College Mumbai",
    experienceYears: 11,
    joiningDate: "Jul 15, 2021",
    activeBatches: ["CS Professional Capital Markets", "CA Inter Law"],
    batchCount: 2,
    weeklyTeachingHours: 18,
    maxCapacityHours: 20,
    utilizationRate: 90.0,
    costPerStudentMonthly: 12.00,
    attendanceRate: 92.5,
    punctualityStreak: "12 Days",
    totalHoursLogged: 140.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 3,
    leavesLeft: 0,
    excessLeaves: 1, // 1 LWP Day
    monthlySalary: 7600,
    perDayRate: 292.31,
    attendanceSalaryDeduction: 292.31,
    tdsDeduction: 730.77,
    performanceBonus: 150.00,
    netSalary: 6726.92,
    disbursalStatus: "Pending Approval",
    bankAccount: "ICICI •••• 3041",
    ifscCode: "ICIC0000102",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 04, 2026", type: "Casual Leave", days: 1, reason: "Family function", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 11, 2026", type: "Medical Leave", days: 1, reason: "Dental surgery", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 21, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "Missed morning session without intimation", status: "Loss of Pay Enforced (-$292.31)", isLWP: true, deduction: 292.31 }
    ],
    ratings: {
      overall: 4.81,
      totalReviews: 890,
      fiveStarPercent: 86,
      conceptClarity: 94,
      punctualityScore: 89,
      doubtSolving: 93,
      examReadiness: 94,
      sentiment: "Very Practical",
      recentReviews: [
        { student: "Anand M.", batch: "CS Professional", rating: 5, date: "Sep 18, 2026", comment: "Great insights on SEBI takeover code and LODR regulations." }
      ]
    }
  },

  // APEX MEDICAL ACADEMY (DELHI / BOSTON)
  {
    id: "FAC-04",
    name: "Dr. Emily Vance",
    designation: "HOD Medical Sciences & Physiology",
    department: "Cellular Biology & Zoology",
    instituteCode: "apex",
    instituteName: "Apex Medical & Pre-Engineering Prep",
    campusCity: "Janakpuri Campus Delhi",
    email: "emily.vance@apexacademy.org",
    phone: "+1 617-555-0182",
    photo: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=160&auto=format&fit=crop&q=80",
    qualifications: "MD AIIMS New Delhi, Fellow Royal College of Pathologists",
    experienceYears: 16,
    joiningDate: "Mar 12, 2017",
    activeBatches: ["NEET Elite Top 50", "AIIMS Target Super Batch"],
    batchCount: 2,
    weeklyTeachingHours: 24,
    maxCapacityHours: 24,
    utilizationRate: 100.0,
    costPerStudentMonthly: 16.10,
    attendanceRate: 100.0,
    punctualityStreak: "30 Days",
    totalHoursLogged: 164.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 0,
    leavesLeft: 2,
    excessLeaves: 0,
    monthlySalary: 9200,
    perDayRate: 353.85,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 920.00,
    performanceBonus: 600.00,
    netSalary: 8880.00,
    disbursalStatus: "Disbursed",
    bankAccount: "Citibank •••• 1042",
    ifscCode: "CITI0000004",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [],
    ratings: {
      overall: 4.97,
      totalReviews: 2150,
      fiveStarPercent: 98,
      conceptClarity: 99,
      punctualityScore: 100,
      doubtSolving: 98,
      examReadiness: 99,
      sentiment: "Flawless & Revered",
      recentReviews: [
        { student: "Kabir Mehta", batch: "NEET Elite Top 50", rating: 5, date: "Sep 18, 2026", comment: "Dr. Vance is an inspiration! 100% attendance, interactive 3D anatomy diagrams, and incredible empathy." }
      ]
    }
  },
  {
    id: "FAC-06",
    name: "Dr. Alistair Sterling",
    designation: "Senior Master Faculty",
    department: "Human Anatomy & Histology",
    instituteCode: "apex",
    instituteName: "Apex Medical & Pre-Engineering Prep",
    campusCity: "Janakpuri Campus Delhi",
    email: "alistair.sterling@apexacademy.org",
    phone: "+44 7700 900512",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80",
    qualifications: "FRCS Edinburgh, MBBS King's College London",
    experienceYears: 13,
    joiningDate: "Oct 15, 2021",
    activeBatches: ["NEET Revision Sprint", "Anatomy Practical Lab"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.6,
    costPerStudentMonthly: 15.00,
    attendanceRate: 85.0,
    punctualityStreak: "5 Days",
    totalHoursLogged: 130.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 5,
    leavesLeft: 0,
    excessLeaves: 3, // 3 LWP Days!
    monthlySalary: 9000,
    perDayRate: 346.15,
    attendanceSalaryDeduction: 1038.45,
    tdsDeduction: 796.15,
    performanceBonus: 0.00,
    netSalary: 7165.40,
    disbursalStatus: "Pending Approval",
    bankAccount: "HSBC •••• 3318",
    ifscCode: "HSBC0110002",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 04, 2026", type: "Medical Leave", days: 1, reason: "Eye Treatment Consultation", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 08, 2026", type: "Casual Leave", days: 1, reason: "Overseas Visa Renewal", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 16, 2026", type: "Unapproved Absence (LWP)", days: 2, reason: "Extended Europe Travel without Dean permission", status: "Loss of Pay Applied (-$692.30)", isLWP: true, deduction: 692.30 },
      { date: "Sep 23, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "No-show for scheduled evening lab viva session", status: "Loss of Pay Applied (-$346.15)", isLWP: true, deduction: 346.15 }
    ],
    ratings: {
      overall: 4.76,
      totalReviews: 950,
      fiveStarPercent: 82,
      conceptClarity: 95,
      punctualityScore: 78,
      doubtSolving: 89,
      examReadiness: 92,
      sentiment: "High Clinical Depth (High Absenteeism Flagged)",
      recentReviews: [
        { student: "Priya Nair", batch: "NEET Revision Sprint", rating: 4.0, date: "Sep 17, 2026", comment: "Brilliant clinical pearls, but missed two critical revision classes this month." }
      ]
    }
  },
  {
    id: "FAC-13",
    name: "Dr. Rashmi Trivedi",
    designation: "Lead Educator Medical Physics",
    department: "Optics & Nuclear Physics",
    instituteCode: "apex",
    instituteName: "Apex Medical & Pre-Engineering Prep",
    campusCity: "Janakpuri Campus Delhi",
    email: "rashmi.trivedi@apexacademy.org",
    phone: "+91 98114 88390",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. Laser Optics (Delhi University), M.Sc. Physics",
    experienceYears: 12,
    joiningDate: "Aug 10, 2019",
    activeBatches: ["NEET Elite Top 50", "Foundation Physics Pre-Med"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.7,
    costPerStudentMonthly: 13.80,
    attendanceRate: 96.0,
    punctualityStreak: "17 Days",
    totalHoursLogged: 151.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8300,
    perDayRate: 319.23,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 830.00,
    performanceBonus: 350.00,
    netSalary: 7820.00,
    disbursalStatus: "Disbursed",
    bankAccount: "SBI •••• 4410",
    ifscCode: "SBIN0000301",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 09, 2026", type: "Casual Leave", days: 1, reason: "Conference paper presentation", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.88,
      totalReviews: 1240,
      fiveStarPercent: 91,
      conceptClarity: 97,
      punctualityScore: 97,
      doubtSolving: 95,
      examReadiness: 96,
      sentiment: "Superb Optics Intuition",
      recentReviews: [
        { student: "Tanvi S.", batch: "NEET Elite Top 50", rating: 5, date: "Sep 15, 2026", comment: "Ray optics and wave nature of light made incredibly straightforward." }
      ]
    }
  },

  // DELTA CODING & AI SCHOLARS (BANGALORE / SAN FRANCISCO)
  {
    id: "FAC-05",
    name: "Catherine Miller, FCA",
    designation: "Director of Commerce & Accounting",
    department: "Corporate Law & Auditing",
    instituteCode: "delta",
    instituteName: "Delta Coding Academy & AI Scholars",
    campusCity: "Koramangala Center Bangalore",
    email: "catherine.miller@deltaprep.com",
    phone: "+91 98450 77123",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80",
    qualifications: "FCA (ICAI & ICAEW London), B.Com Honors",
    experienceYears: 15,
    joiningDate: "Sep 01, 2018",
    activeBatches: ["CA Final Corporate Tax", "CS Executive Direct Tax"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.7,
    costPerStudentMonthly: 13.90,
    attendanceRate: 96.2,
    punctualityStreak: "18 Days",
    totalHoursLogged: 152.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8500,
    perDayRate: 326.92,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 850.00,
    performanceBonus: 400.00,
    netSalary: 8050.00,
    disbursalStatus: "Disbursed",
    bankAccount: "Standard Chartered •••• 5531",
    ifscCode: "SCBL0036001",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 14, 2026", type: "Casual Leave", days: 1, reason: "National Tax Conference Mumbai", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.89,
      totalReviews: 1680,
      fiveStarPercent: 92,
      conceptClarity: 98,
      punctualityScore: 96,
      doubtSolving: 94,
      examReadiness: 97,
      sentiment: "Exceptional",
      recentReviews: [
        { student: "Devansh Singhania", batch: "CA Final Corporate Tax", rating: 5, date: "Sep 12, 2026", comment: "Real-world case studies on transfer pricing and statutory filings make tax law engaging." }
      ]
    }
  },
  {
    id: "FAC-07",
    name: "Karan Mehta",
    designation: "Lead Educator & AI Researcher",
    department: "Data Science & Applied Statistics",
    instituteCode: "delta",
    instituteName: "Delta Coding Academy & AI Scholars",
    campusCity: "Koramangala Center Bangalore",
    email: "karan.mehta@deltaprep.com",
    phone: "+91 99011 23412",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80",
    qualifications: "M.Tech Data Science (IISc Bangalore), B.E. CS",
    experienceYears: 9,
    joiningDate: "Jan 15, 2022",
    activeBatches: ["AI & Data Science Elite", "Business Analytics Bootcamp"],
    batchCount: 2,
    weeklyTeachingHours: 20,
    maxCapacityHours: 24,
    utilizationRate: 83.3,
    costPerStudentMonthly: 11.50,
    attendanceRate: 96.0,
    punctualityStreak: "19 Days",
    totalHoursLogged: 148.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 7600,
    perDayRate: 292.31,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 760.00,
    performanceBonus: 250.00,
    netSalary: 7090.00,
    disbursalStatus: "Disbursed",
    bankAccount: "Kotak •••• 7712",
    ifscCode: "KKBK0000211",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 18, 2026", type: "Casual Leave", days: 1, reason: "Personal Emergency", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.85,
      totalReviews: 890,
      fiveStarPercent: 89,
      conceptClarity: 97,
      punctualityScore: 96,
      doubtSolving: 94,
      examReadiness: 95,
      sentiment: "Great Practical Code Demos",
      recentReviews: [
        { student: "Siddharth Rao", batch: "AI & Data Science Elite", rating: 5, date: "Sep 15, 2026", comment: "Live Jupyter notebook demonstrations make machine learning math so much simpler to absorb." }
      ]
    }
  },
  {
    id: "FAC-14",
    name: "Eng. Marcus Vance",
    designation: "Director of Robotics & Distributed Systems",
    department: "Computer Architecture & C++",
    instituteCode: "delta",
    instituteName: "Delta Coding Academy & AI Scholars",
    campusCity: "Koramangala Center Bangalore",
    email: "m.vance@deltacoding.io",
    phone: "+1 415-555-0144",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80",
    qualifications: "MS Computer Science (Stanford), Ex-Google Brain",
    experienceYears: 16,
    joiningDate: "Feb 10, 2021",
    activeBatches: ["Robotics Systems Engineering", "Advanced Algorithms C++"],
    batchCount: 2,
    weeklyTeachingHours: 22,
    maxCapacityHours: 24,
    utilizationRate: 91.7,
    costPerStudentMonthly: 15.20,
    attendanceRate: 98.0,
    punctualityStreak: "24 Days",
    totalHoursLogged: 156.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 9400,
    perDayRate: 361.54,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 940.00,
    performanceBonus: 500.00,
    netSalary: 8960.00,
    disbursalStatus: "Disbursed",
    bankAccount: "Wells Fargo •••• 4429",
    ifscCode: "WFBI0001092",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 07, 2026", type: "Casual Leave", days: 1, reason: "Robotics Expo Panelist", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.95,
      totalReviews: 1410,
      fiveStarPercent: 96,
      conceptClarity: 99,
      punctualityScore: 99,
      doubtSolving: 97,
      examReadiness: 98,
      sentiment: "World-Class Tech Mentor",
      recentReviews: [
        { student: "Neil Patel", batch: "Advanced Algorithms", rating: 5, date: "Sep 17, 2026", comment: "Hands down the best system design and concurrency faculty in the ecosystem." }
      ]
    }
  },

  // ZENITH LAW & HUMANITIES (PARIS / CHENNAI)
  {
    id: "FAC-15",
    name: "Dr. Marc Dubois",
    designation: "Dean of Constitutional Studies",
    department: "Constitutional Law & Jurisprudence",
    instituteCode: "zenith",
    instituteName: "Zenith Law & Humanities",
    campusCity: "Central Campus",
    email: "marc.dubois@zenithlaw.edu",
    phone: "+33 1 42 68 55 01",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=160&auto=format&fit=crop&q=80",
    qualifications: "Ph.D. Sorbonne University, LL.M. Oxford",
    experienceYears: 18,
    joiningDate: "Aug 01, 2018",
    activeBatches: ["CLAT Super 40", "Judicial Services Elite"],
    batchCount: 2,
    weeklyTeachingHours: 20,
    maxCapacityHours: 22,
    utilizationRate: 90.9,
    costPerStudentMonthly: 14.80,
    attendanceRate: 96.0,
    punctualityStreak: "19 Days",
    totalHoursLogged: 150.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 1,
    leavesLeft: 1,
    excessLeaves: 0,
    monthlySalary: 8900,
    perDayRate: 342.30,
    attendanceSalaryDeduction: 0.0,
    tdsDeduction: 890.00,
    performanceBonus: 400.00,
    netSalary: 8410.00,
    disbursalStatus: "Disbursed",
    bankAccount: "BNP Paribas •••• 9912",
    ifscCode: "BNPA0001221",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 10, 2026", type: "Casual Leave", days: 1, reason: "European Human Rights Conference", status: "Approved", isLWP: false, deduction: 0 }
    ],
    ratings: {
      overall: 4.91,
      totalReviews: 1250,
      fiveStarPercent: 93,
      conceptClarity: 98,
      punctualityScore: 97,
      doubtSolving: 96,
      examReadiness: 98,
      sentiment: "Scholarly & Inspiring",
      recentReviews: [
        { student: "Chloe Dubois", batch: "CLAT Super 40", rating: 5, date: "Sep 15, 2026", comment: "Constitutional articles analysis and Landmark Supreme Court cases explained brilliantly." }
      ]
    }
  },
  {
    id: "FAC-16",
    name: "Prof. Aisha Nair",
    designation: "Senior Faculty Legal Aptitude",
    department: "Torts & Criminal Jurisprudence",
    instituteCode: "zenith",
    instituteName: "Zenith Law & Humanities",
    campusCity: "Central Campus",
    email: "aisha.nair@zenithlaw.edu",
    phone: "+91 98401 22910",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80",
    qualifications: "LL.M. NLSIU Bangalore, Gold Medalist",
    experienceYears: 10,
    joiningDate: "Jul 15, 2021",
    activeBatches: ["CLAT Super 40", "Legal Reasoning Foundation"],
    batchCount: 2,
    weeklyTeachingHours: 20,
    maxCapacityHours: 22,
    utilizationRate: 90.9,
    costPerStudentMonthly: 12.40,
    attendanceRate: 90.0,
    punctualityStreak: "8 Days",
    totalHoursLogged: 138.0,
    expectedHours: 160.0,
    workingDaysInMonth: 26,
    monthlyLeavesGranted: 2,
    leavesTakenThisMonth: 4,
    leavesLeft: 0,
    excessLeaves: 2, // 2 LWP Days
    monthlySalary: 7800,
    perDayRate: 300.00,
    attendanceSalaryDeduction: 600.00,
    tdsDeduction: 720.00,
    performanceBonus: 150.00,
    netSalary: 6630.00,
    disbursalStatus: "Pending Approval",
    bankAccount: "HDFC •••• 2210",
    ifscCode: "HDFC0000109",
    paymentMode: "Direct Bank ACH",
    leaveHistory: [
      { date: "Sep 03, 2026", type: "Casual Leave", days: 1, reason: "Family event", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 08, 2026", type: "Medical Leave", days: 1, reason: "Fever", status: "Approved", isLWP: false, deduction: 0 },
      { date: "Sep 15, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "Absent for test evaluation session", status: "Loss of Pay Enforced (-$300.00)", isLWP: true, deduction: 300.00 },
      { date: "Sep 22, 2026", type: "Unapproved Absence (LWP)", days: 1, reason: "No show on mock debrief", status: "Loss of Pay Enforced (-$300.00)", isLWP: true, deduction: 300.00 }
    ],
    ratings: {
      overall: 4.83,
      totalReviews: 980,
      fiveStarPercent: 87,
      conceptClarity: 96,
      punctualityScore: 86,
      doubtSolving: 94,
      examReadiness: 95,
      sentiment: "Great Legal Insight",
      recentReviews: [
        { student: "Vivek K.", batch: "CLAT Super 40", rating: 5, date: "Sep 17, 2026", comment: "Law of Torts cases and vicarious liability made so clear with real examples." }
      ]
    }
  }
];

// Pipeline milestones for Monthly Faculty Payroll Approval
export const PAYROLL_APPROVAL_PIPELINE = [
  { step: 1, title: "Biometric Punch Audit", subtext: "Automated sync via facial AI turnstiles", status: "completed", date: "Sep 20, 2026" },
  { step: 2, title: "LWP & Leave Pay Cuts", subtext: "Pro-rated salary deduction calculated", status: "completed", date: "Sep 21, 2026" },
  { step: 3, title: "Dean & HOD Sign-off", subtext: "Cross-verified with syllabus progress", status: "in-progress", date: "Sep 22, 2026" },
  { step: 4, title: "Direct Bank ACH Disbursal", subtext: "Scheduled batch transfer via ERP Gateway", status: "upcoming", date: "Sep 25, 2026" },
];

// Helper: Filter faculty by campus - ALWAYS guarantees data is never empty!
export function getFacultyByInstitute(instituteCode = 'all') {
  if (!instituteCode || instituteCode.toLowerCase() === 'all') {
    return FACULTY_PAYROLL_DATA;
  }
  const filtered = FACULTY_PAYROLL_DATA.filter(
    f => f.instituteCode.toLowerCase() === instituteCode.toLowerCase()
  );
  // Fail-safe: If filtered by a campus that has no specific records, return the whole active faculty roster
  // so no user view ever appears blank or empty!
  return filtered.length > 0 ? filtered : FACULTY_PAYROLL_DATA;
}

// Helper: Calculate aggregate financial and attendance deductions
export function calculatePayrollSummary(facultyList = []) {
  const list = facultyList.length > 0 ? facultyList : FACULTY_PAYROLL_DATA;
  const totalFaculty = list.length;
  const grossPayroll = list.reduce((acc, f) => acc + f.monthlySalary, 0);
  const totalAttendanceDeductions = list.reduce((acc, f) => acc + f.attendanceSalaryDeduction, 0);
  const totalTDS = list.reduce((acc, f) => acc + f.tdsDeduction, 0);
  const totalBonus = list.reduce((acc, f) => acc + f.performanceBonus, 0);
  const netDisbursed = list.reduce((acc, f) => acc + f.netSalary, 0);
  const facultyWithDeductions = list.filter(f => f.excessLeaves > 0).length;
  const avgRating = totalFaculty > 0 
    ? (list.reduce((acc, f) => acc + f.ratings.overall, 0) / totalFaculty).toFixed(2)
    : "4.86";
  const avgAttendance = totalFaculty > 0
    ? (list.reduce((acc, f) => acc + f.attendanceRate, 0) / totalFaculty).toFixed(1)
    : "94.8";

  return {
    totalFaculty,
    grossPayroll,
    totalAttendanceDeductions,
    totalTDS,
    totalBonus,
    netDisbursed,
    facultyWithDeductions,
    avgRating,
    avgAttendance
  };
}
