// Comprehensive Mock Datasets for Module 17: SMTP / Email Gateway & Multi-Channel Communications

export const CAMPAIGNS_DATA = [
  {
    id: 'CMP-701',
    title: 'JEE Advanced Mock-5 Scorecard & Analysis Blast',
    channel: 'Email',
    targetAudience: 'Grade 12 • JEE Super-30 & Foundation (Kota & Delhi)',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    totalRecipients: 420,
    delivered: 418,
    opened: 362,
    openRate: '86.6%',
    clicked: 215,
    clickRate: '51.4%',
    bounced: 2,
    status: 'Completed',
    dispatchedDate: 'Today, 08:30 AM IST',
    senderAddress: 'results@alpha-kota.edu.in',
    subject: 'Aarav’s Performance Dossier: JEE Advanced Mock Test #5 Analysis',
    templateUsed: 'Monthly Academic Progress Card'
  },
  {
    id: 'CMP-702',
    title: 'Quarterly Tuition Fee Due & Olympiad Concession Alert',
    channel: 'Dual (Email + SMS)',
    targetAudience: 'All Campuses • Pending 2nd Installment Defaulters',
    instituteCode: 'global',
    instituteName: 'Global Multi-Tenant HQ',
    totalRecipients: 180,
    delivered: 179,
    opened: 145,
    openRate: '81.0%',
    clicked: 98,
    clickRate: '54.7%',
    bounced: 1,
    status: 'Active',
    dispatchedDate: 'Today, 10:15 AM IST',
    senderAddress: 'finance@eduzenith-cloud.com',
    subject: 'Urgent: Q3 Tuition Installment Due Date & UPI Payment Gateway Link',
    templateUsed: 'Fee Due Notice (DLT-Approved)'
  },
  {
    id: 'CMP-703',
    title: 'Emergency Torrential Rain Class Holiday Circular',
    channel: 'SMS',
    targetAudience: 'Beta Commerce Academy • Mumbai Campuses (All Batches)',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    totalRecipients: 890,
    delivered: 888,
    opened: 860,
    openRate: '96.8%',
    clicked: 540,
    clickRate: '60.8%',
    bounced: 2,
    status: 'Completed',
    dispatchedDate: 'Yesterday, 06:45 AM IST',
    senderAddress: 'SMS Header: ZENITH-MUM',
    subject: 'Alert: Offline classes suspended due to IMD red alert; switch to WebRTC live stream.',
    templateUsed: 'Emergency Holiday Alert (DLT: 140716...)'
  },
  {
    id: 'CMP-704',
    title: 'Parent-Teacher Meeting (PTM) Slot Booking Invitation',
    channel: 'Email',
    targetAudience: 'Apex Medical Prep • NEET Batch Alpha & Beta',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    totalRecipients: 240,
    delivered: 239,
    opened: 198,
    openRate: '82.8%',
    clicked: 168,
    clickRate: '70.3%',
    bounced: 1,
    status: 'Completed',
    dispatchedDate: 'Yesterday, 02:00 PM IST',
    senderAddress: 'counseling@apex-delhi.org',
    subject: 'Schedule Your 1-on-1 Faculty PTM Session for September 2026',
    templateUsed: 'Parent PTM Booking Invite'
  },
  {
    id: 'CMP-705',
    title: 'International Informatics Olympiad (IOI) Bootcamp Selection',
    channel: 'Email',
    targetAudience: 'Delta Coding Academy • Advanced AI Scholars',
    instituteCode: 'delta',
    instituteName: 'Delta Coding Academy',
    totalRecipients: 65,
    delivered: 65,
    opened: 62,
    openRate: '95.4%',
    clicked: 58,
    clickRate: '89.2%',
    bounced: 0,
    status: 'Completed',
    dispatchedDate: 'Sep 17, 2026 • 11:30 AM IST',
    senderAddress: 'dean@delta-academy.io',
    subject: 'Congratulations: You have been shortlisted for IOI 2026 Residential Bootcamp',
    templateUsed: 'Olympiad Selection Letter'
  },
  {
    id: 'CMP-706',
    title: 'Constitution Day National Mock CLAT Registration Open',
    channel: 'Dual (Email + SMS)',
    targetAudience: 'Zenith Humanities & Law • All Prospective Leads',
    instituteCode: 'zenith',
    instituteName: 'Zenith Humanities & Law',
    totalRecipients: 1250,
    delivered: 1242,
    opened: 790,
    openRate: '63.6%',
    clicked: 340,
    clickRate: '27.4%',
    bounced: 8,
    status: 'Scheduled',
    dispatchedDate: 'Sep 24, 2026 • 09:00 AM IST (Queued)',
    senderAddress: 'admissions@zenith-law.org',
    subject: 'National Scholarship Test 2026: Up to 100% Fee Waiver for Top 50 Ranks',
    templateUsed: 'National Scholarship Blast'
  }
];

export const TEMPLATES_DATA = [
  {
    id: 'TMP-EML-01',
    type: 'Email',
    category: 'Academics',
    name: 'Monthly Progress Card & Digital Dossier',
    subject: '{{student_name}} - {{month_year}} Academic Report & Rank Card',
    variables: ['{{student_name}}', '{{roll_number}}', '{{batch_name}}', '{{month_year}}', '{{attendance_pct}}', '{{score_avg}}', '{{portal_link}}'],
    previewText: 'Dear {{parent_name}}, your ward {{student_name}} achieved {{attendance_pct}}% attendance and {{score_avg}}% in {{month_year}} tests. Click to view and digitally sign.',
    usageCount: 4890,
    status: 'Approved & Active',
    format: 'HTML Rich Responsive',
    lastModified: 'Sep 02, 2026'
  },
  {
    id: 'TMP-EML-02',
    type: 'Email',
    category: 'Finance',
    name: 'Fee Receipt & GST Tax Invoice',
    subject: 'Official Fee Receipt #{{receipt_no}} - {{institute_name}}',
    variables: ['{{parent_name}}', '{{student_name}}', '{{receipt_no}}', '{{amount_paid}}', '{{mode}}', '{{balance_due}}', '{{invoice_pdf_link}}'],
    previewText: 'Payment confirmation for {{student_name}}. Received INR {{amount_paid}} via {{mode}}. Download official GST-compliant tax invoice.',
    usageCount: 3410,
    status: 'Approved & Active',
    format: 'HTML Rich Responsive',
    lastModified: 'Aug 28, 2026'
  },
  {
    id: 'TMP-EML-03',
    type: 'Email',
    category: 'Administration',
    name: 'Parent PTM Booking & Google Meet Link',
    subject: 'Confirmed Consultation: PTM Slot for {{student_name}} on {{meeting_date}}',
    variables: ['{{parent_name}}', '{{faculty_name}}', '{{student_name}}', '{{meeting_date}}', '{{time_slot}}', '{{meet_url}}', '{{room_number}}'],
    previewText: 'Your consultation with {{faculty_name}} is confirmed for {{meeting_date}} at {{time_slot}}. Join virtual room or visit {{room_number}}.',
    usageCount: 940,
    status: 'Approved & Active',
    format: 'HTML Rich Responsive',
    lastModified: 'Sep 10, 2026'
  },
  {
    id: 'TMP-SMS-01',
    type: 'SMS',
    category: 'Security & Operations',
    name: 'Latecomer Facial Biometrics Gate Alert',
    dltId: 'DLT-140716889211029',
    subject: 'SMS Header: ZENITH-GATE',
    variables: ['{{student_name}}', '{{time}}', '{{campus_name}}'],
    previewText: 'Dear Parent, your ward {{student_name}} checked in late at {{campus_name}} gate at {{time}}. Automated biometric facial alert. Zenith ERP.',
    charCount: 138,
    usageCount: 12450,
    status: 'DLT Registered (TRAI)',
    format: 'GSM 7-bit (160 char limit)',
    lastModified: 'Aug 15, 2026'
  },
  {
    id: 'TMP-SMS-02',
    type: 'SMS',
    category: 'Finance',
    name: 'Fee Installment Due Date Push Reminder',
    dltId: 'DLT-140716889211030',
    subject: 'SMS Header: ZENITH-FEE',
    variables: ['{{student_name}}', '{{amount}}', '{{due_date}}', '{{pay_link}}'],
    previewText: 'Zenith Alert: Q3 fee for {{student_name}} of Rs. {{amount}} is due on {{due_date}}. Pay via UPI/Card to avoid late fee: {{pay_link}}',
    charCount: 142,
    usageCount: 8200,
    status: 'DLT Registered (TRAI)',
    format: 'GSM 7-bit (160 char limit)',
    lastModified: 'Sep 01, 2026'
  },
  {
    id: 'TMP-SMS-03',
    type: 'SMS',
    category: 'Security & Auth',
    name: 'Parent Portal Login OTP Verification',
    dltId: 'DLT-140716889211031',
    subject: 'SMS Header: ZENITH-OTP',
    variables: ['{{otp_code}}', '{{validity}}'],
    previewText: 'Your Zenith Parent Portal verification OTP is {{otp_code}}. Valid for {{validity}} minutes. Do not share this code with anyone.',
    charCount: 124,
    usageCount: 28400,
    status: 'DLT Registered (TRAI)',
    format: 'GSM 7-bit (160 char limit)',
    lastModified: 'Jul 20, 2026'
  }
];

export const SEND_HISTORY_LOGS = [
  {
    id: 'MSG-88401',
    channel: 'Email',
    recipient: 'sunita.sharma@gmail.com',
    recipientName: 'Sunita Sharma (Parent)',
    studentRoll: 'KOTA-JEE-042',
    subject: 'Aarav Sharma - August 2026 Academic Dossier & Scorecard',
    campaignOrTemplate: 'Monthly Progress Card & Digital Dossier',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    timestamp: 'Today, 08:30:12 AM IST',
    relayServer: 'aws-ses-mumbai-01.eduzenith.net',
    smtpCode: '250 2.0.0 OK: Delivered to mx.google.com',
    openStatus: 'Opened (Today, 08:42 AM)',
    deliveryStatus: 'Delivered',
    payloadSize: '42.8 KB'
  },
  {
    id: 'MSG-88402',
    channel: 'SMS',
    recipient: '+91 98234-11002',
    recipientName: 'Sunita Sharma (Parent)',
    studentRoll: 'KOTA-JEE-042',
    subject: 'Biometric Turnstile Check-in Alert (Time: 07:58 AM)',
    campaignOrTemplate: 'Latecomer Facial Biometrics Gate Alert',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    timestamp: 'Today, 07:58:04 AM IST',
    relayServer: 'Gupshup DLT Gateway (Telco: Airtel)',
    smtpCode: 'DELIVRD (ACK: 0x00)',
    openStatus: 'Handset Received',
    deliveryStatus: 'Delivered',
    payloadSize: '138 Chars'
  },
  {
    id: 'MSG-88403',
    channel: 'Email',
    recipient: 'rajesh.mehta@mumbaicorp.in',
    recipientName: 'Rajesh Mehta (Parent)',
    studentRoll: 'MUM-CA-108',
    subject: 'Confirmed Consultation: PTM Slot for Riya Mehta on Sep 21',
    campaignOrTemplate: 'Parent PTM Booking & Google Meet Link',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    timestamp: 'Today, 09:12:30 AM IST',
    relayServer: 'aws-ses-mumbai-01.eduzenith.net',
    smtpCode: '250 2.0.0 OK: Delivered to mail.mumbaicorp.in',
    openStatus: 'Opened & Clicked Link',
    deliveryStatus: 'Delivered',
    payloadSize: '36.2 KB'
  },
  {
    id: 'MSG-88404',
    channel: 'SMS',
    recipient: '+91 98112-99834',
    recipientName: 'Rajesh Mehta (Parent)',
    studentRoll: 'MUM-CA-108',
    subject: 'Emergency Rain Holiday Circular (Beta Academy)',
    campaignOrTemplate: 'Emergency Holiday Alert',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    timestamp: 'Yesterday, 06:45:10 AM IST',
    relayServer: 'Twilio India SMS Relay (Telco: Jio)',
    smtpCode: 'DELIVRD (ACK: 0x00)',
    openStatus: 'Handset Received',
    deliveryStatus: 'Delivered',
    payloadSize: '142 Chars'
  },
  {
    id: 'MSG-88405',
    channel: 'Email',
    recipient: 'anita.deshmukh@aiims.org',
    recipientName: 'Dr. Anita Deshmukh',
    studentRoll: 'DEL-NEET-219',
    subject: 'Official Fee Receipt #REC-2026-9902 - Apex Medical Prep',
    campaignOrTemplate: 'Fee Receipt & GST Tax Invoice',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    timestamp: 'Yesterday, 04:15:00 PM IST',
    relayServer: 'postfix-eu-relay.eduzenith.net',
    smtpCode: '250 2.0.0 OK: Delivered to mx.aiims.org',
    openStatus: 'Opened (Yesterday, 05:02 PM)',
    deliveryStatus: 'Delivered',
    payloadSize: '58.4 KB'
  },
  {
    id: 'MSG-88406',
    channel: 'Email',
    recipient: 'invalid.parent@fakeemail-unknown.com',
    recipientName: 'Disowned Contact Record',
    studentRoll: 'BLR-AI-999',
    subject: 'Quarterly Tuition Fee Due Reminder',
    campaignOrTemplate: 'Quarterly Tuition Fee Due Alert',
    instituteCode: 'delta',
    instituteName: 'Delta Coding Academy',
    timestamp: 'Yesterday, 02:10:18 PM IST',
    relayServer: 'aws-ses-mumbai-01.eduzenith.net',
    smtpCode: '550 5.1.1 Host or domain name not found',
    openStatus: 'Unread (Bounced)',
    deliveryStatus: 'Bounced',
    payloadSize: '24.1 KB'
  },
  {
    id: 'MSG-88407',
    channel: 'SMS',
    recipient: '+91 97654-32110',
    recipientName: 'Dr. Anita Deshmukh',
    studentRoll: 'DEL-NEET-219',
    subject: 'Parent Portal Login OTP: 849201',
    campaignOrTemplate: 'Parent Portal Login OTP Verification',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    timestamp: 'Sep 17, 2026 • 07:12 PM IST',
    relayServer: 'Gupshup DLT Gateway (Telco: Vi)',
    smtpCode: 'DELIVRD (ACK: 0x00)',
    openStatus: 'Handset Received',
    deliveryStatus: 'Delivered',
    payloadSize: '124 Chars'
  },
  {
    id: 'MSG-88408',
    channel: 'Email',
    recipient: 'suresh.reddy@highcourt.gov.in',
    recipientName: 'Adv. Suresh Reddy',
    studentRoll: 'HYD-CLAT-077',
    subject: 'National Mock CLAT Exam Schedule & Syllabus Guidelines',
    campaignOrTemplate: 'National Scholarship Blast',
    instituteCode: 'zenith',
    instituteName: 'Zenith Humanities & Law',
    timestamp: 'Sep 17, 2026 • 10:05 AM IST',
    relayServer: 'aws-ses-mumbai-01.eduzenith.net',
    smtpCode: '250 2.0.0 OK: Delivered to nic.in mail exchanger',
    openStatus: 'Opened (Sep 17, 11:20 AM)',
    deliveryStatus: 'Delivered',
    payloadSize: '51.6 KB'
  }
];

export const RELAY_NODES_DATA = [
  {
    id: 'NODE-01',
    name: 'AWS SES Production Cluster (Mumbai ap-south-1)',
    protocol: 'SMTP / TLS 1.3 Strict',
    host: 'email-smtp.ap-south-1.amazonaws.com',
    port: 587,
    status: 'Optimal / Green',
    reputationScore: '99.4%',
    dailyQuota: '48,920 / 100,000 Sent',
    quotaPercent: 48.9,
    latencyMs: 38,
    spfStatus: 'PASS (v=spf1 include:amazonses.com ~all)',
    dkimStatus: 'PASS (2048-bit RSA Validated)',
    dmarcStatus: 'PASS (p=reject strict alignment)',
    tlsEncryption: 'TLS_AES_256_GCM_SHA384'
  },
  {
    id: 'NODE-02',
    name: 'Secondary Postfix Relay (Frankfurt eu-central-1)',
    protocol: 'SMTP / TLS 1.3',
    host: 'smtp-relay-02.eduzenith.net',
    port: 465,
    status: 'Standby / Warm',
    reputationScore: '98.8%',
    dailyQuota: '1,240 / 50,000 Sent',
    quotaPercent: 2.5,
    latencyMs: 142,
    spfStatus: 'PASS (v=spf1 ip4:185.22.10.0/24 ~all)',
    dkimStatus: 'PASS (2048-bit RSA Validated)',
    dmarcStatus: 'PASS (Aligned)',
    tlsEncryption: 'TLS_CHACHA20_POLY1305_SHA256'
  },
  {
    id: 'NODE-03',
    name: 'Gupshup Enterprise SMS DLT Gateway (India Telecom)',
    protocol: 'SMPP v3.4 / REST HTTPS',
    host: 'api.gupshup.io/smpp/gateway',
    port: 2775,
    status: 'Optimal / Green',
    reputationScore: '99.9%',
    dailyQuota: '62,140 / 250,000 SMS',
    quotaPercent: 24.8,
    latencyMs: 64,
    spfStatus: 'TRAI Registered Principal Entity: 1101...',
    dkimStatus: 'Header ZENITH-GATE, ZENITH-FEE Whitelisted',
    dmarcStatus: 'TRAI DLT Telemetry Compliant',
    tlsEncryption: 'HTTPS TLS 1.3 / AES-256'
  }
];

export const REPORTS_DATA = {
  deliverability: {
    overallRate: '99.82%',
    emailSent: 48920,
    smsDelivered: 62140,
    meanOpenRate: '68.4%',
    meanClickRate: '34.2%',
    peakHour: '07:30 PM - 08:45 PM IST',
    monthlyTrend: [
      { month: 'Apr', emails: 42100, delivered: 42010, rate: '99.78%' },
      { month: 'May', emails: 44500, delivered: 44420, rate: '99.82%' },
      { month: 'Jun', emails: 47200, delivered: 47120, rate: '99.83%' },
      { month: 'Jul', emails: 46800, delivered: 46710, rate: '99.80%' },
      { month: 'Aug', emails: 48920, delivered: 48832, rate: '99.82%', current: true },
      { month: 'Sep (P)', emails: 49400, delivered: 49320, rate: '99.84%' }
    ],
    campusResponsiveness: [
      { campus: 'Alpha Institute of Science & Tech', sent: 16400, openRate: '72.4%', clickRate: '38.2%', status: 'Exemplary' },
      { campus: 'Beta Commerce Academy (CA)', sent: 12100, openRate: '69.1%', clickRate: '35.0%', status: 'Optimal' },
      { campus: 'Apex Medical Prep', sent: 11800, openRate: '67.5%', clickRate: '33.8%', status: 'Optimal' },
      { campus: 'Delta Coding Academy', sent: 4820, openRate: '78.2%', clickRate: '46.1%', status: 'Fast Track' },
      { campus: 'Zenith Humanities & Law', sent: 3800, openRate: '59.8%', clickRate: '24.5%', status: 'Standard' }
    ]
  },
  bounceAudit: {
    totalBounces: 18,
    bounceRate: '0.036%',
    spamComplaints: 4,
    spamRate: '0.008%',
    senderScore: '99 / 100 Clean IP',
    autoQuarantined: 18,
    categories: [
      { reason: '550 5.1.1 Recipient Domain / Mailbox Not Found', count: 9, percentage: 50, color: 'bg-rose-600' },
      { reason: '552 5.2.2 Mailbox Quota Full (Parent Storage Exceeded)', count: 5, percentage: 28, color: 'bg-amber-600' },
      { reason: 'DLT SMS Carrier Number Suspended / Swapped', count: 3, percentage: 17, color: 'bg-indigo-600' },
      { reason: 'ISP Greylisting / Connection Rate Limit', count: 1, percentage: 5, color: 'bg-blue-600' }
    ],
    quarantineList: [
      { address: 'invalid.parent@fakeemail-unknown.com', type: 'Email', campus: 'Delta Coding Academy', bounceType: 'Hard Bounce (Domain Not Found)', date: 'Sep 18, 2026', action: 'Auto-Purged from Mailer' },
      { address: '+91 99999-00000', type: 'SMS', campus: 'Alpha Institute', bounceType: 'Invalid Number (DLT Rejection)', date: 'Sep 17, 2026', action: 'Blacklisted' },
      { address: 'full.inbox@legacymail.net', type: 'Email', campus: 'Beta Commerce Academy', bounceType: 'Soft Bounce (Mailbox Full)', date: 'Sep 16, 2026', action: 'Retry Scheduled (3 of 5)' }
    ]
  }
};
