// Comprehensive Mock Datasets for Module 07: Parent App & PTM (Multi-Tenant Cloud ERP)

export const PTM_MEETINGS_DATA = [
  {
    id: 'PTM-801',
    parentName: 'Sunita Sharma',
    parentPhone: '+91 98234-11002',
    parentEmail: 'sunita.sharma@gmail.com',
    studentName: 'Aarav Sharma',
    studentRoll: 'KOTA-JEE-042',
    gradeBatch: 'Grade 12 • JEE Super-30 Batch',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    facultyName: 'Dr. V. K. Bansal',
    facultySubject: 'Advanced Physics (Mechanics)',
    date: 'Sep 21, 2026',
    timeSlot: '10:30 AM - 10:55 AM',
    meetingType: 'In-Person Classroom',
    roomLocation: 'Room 304, Academic Block A',
    agenda: 'Rotational Dynamics test performance & JEE Advanced problem-solving speed pacing.',
    status: 'Confirmed',
    priority: 'High',
    parentNotes: 'Aarav is taking 45 mins extra on Physics Section B. Need guidance on question selection strategy.',
    facultySummary: 'Student has high conceptual clarity; needs time-boxing drills.'
  },
  {
    id: 'PTM-802',
    parentName: 'Rajesh Mehta',
    parentPhone: '+91 98112-99834',
    parentEmail: 'rajesh.mehta@mumbaicorp.in',
    studentName: 'Riya Mehta',
    studentRoll: 'MUM-CA-108',
    gradeBatch: 'CA Foundation • Batch Alpha',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    facultyName: 'CA Anand Singhania',
    facultySubject: 'Principles of Accounting & Mercantile Law',
    date: 'Sep 21, 2026',
    timeSlot: '11:15 AM - 11:40 AM',
    meetingType: 'Google Meet Video',
    roomLocation: 'meet.google.com/zen-ptm-mumbai',
    agenda: 'Partnership Accounts quiz review and Law section answer presentation formatting.',
    status: 'Confirmed',
    priority: 'Normal',
    parentNotes: 'Father traveling to Pune; requested virtual video link.',
    facultySummary: 'Excellent retention; needs to improve handwritten speed.'
  },
  {
    id: 'PTM-803',
    parentName: 'Dr. Anita Deshmukh',
    parentPhone: '+91 97654-32110',
    parentEmail: 'anita.deshmukh@aiims.org',
    studentName: 'Kabir Deshmukh',
    studentRoll: 'DEL-NEET-219',
    gradeBatch: 'Grade 11 • NEET Target AIIMS',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    facultyName: 'Dr. Shalini Varma',
    facultySubject: 'Human Anatomy & Zoology',
    date: 'Sep 21, 2026',
    timeSlot: '02:00 PM - 02:25 PM',
    meetingType: 'In-Person Classroom',
    roomLocation: 'Counseling Cell, 2nd Floor',
    agenda: 'Botany diagram scoring criteria and NCERT line-by-line revision tracking.',
    status: 'Confirmed',
    priority: 'High',
    parentNotes: 'Mother seeking clarity on internal test negative marking pattern.',
    facultySummary: 'Consistent top 5% in Zoology; Botany morphology requires extra attention.'
  },
  {
    id: 'PTM-804',
    parentName: 'Karthik Ramanathan',
    parentPhone: '+91 99441-23891',
    parentEmail: 'karthik.r@techblr.io',
    studentName: 'Ananya Ramanathan',
    studentRoll: 'BLR-AI-014',
    gradeBatch: 'Grade 10 • AI & Olympiad FastTrack',
    instituteCode: 'delta',
    instituteName: 'Delta Coding Academy',
    facultyName: 'Prof. Arvind Nambiar',
    facultySubject: 'Data Structures & Python Algorithmic Logic',
    date: 'Sep 22, 2026',
    timeSlot: '10:00 AM - 10:25 AM',
    meetingType: 'Google Meet Video',
    roomLocation: 'meet.google.com/zen-ptm-delta',
    agenda: 'International Informatics Olympiad (IOI) qualification roadmap & mentor allocation.',
    status: 'Requested',
    priority: 'Critical',
    parentNotes: 'Parent wants to discuss fast-tracking Graph Theory curriculum before October camp.',
    facultySummary: 'Exceptional coder; recommended for Advanced Competitive Cohort.'
  },
  {
    id: 'PTM-805',
    parentName: 'Adv. Suresh Reddy',
    parentPhone: '+91 98490-55612',
    parentEmail: 'suresh.reddy@highcourt.gov.in',
    studentName: 'Varun Reddy',
    studentRoll: 'HYD-CLAT-077',
    gradeBatch: 'Grade 12 • CLAT & NALSAR Prime',
    instituteCode: 'zenith',
    instituteName: 'Zenith Humanities & Law',
    facultyName: 'Adv. Meenakshi Sundaram',
    facultySubject: 'Legal Reasoning & Constitutional Law',
    date: 'Sep 22, 2026',
    timeSlot: '11:30 AM - 11:55 AM',
    meetingType: 'In-Person Classroom',
    roomLocation: 'Moot Court Hall, 1st Floor',
    agenda: 'Reading speed benchmark (350 wpm target) for Legal GK & Passage Reading comprehension.',
    status: 'Confirmed',
    priority: 'Normal',
    parentNotes: 'Discussing mock test rank variance between offline and online testing.',
    facultySummary: 'Strong argumentative skills; speed drills will boost rank by 200 places.'
  },
  {
    id: 'PTM-806',
    parentName: 'Bhavna Chawla',
    parentPhone: '+91 98190-44321',
    parentEmail: 'bhavna.c@gmail.com',
    studentName: 'Rohan Chawla',
    studentRoll: 'KOTA-JEE-098',
    gradeBatch: 'Grade 11 • JEE Foundation Batch',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    facultyName: 'Er. R. C. Mukherjee',
    facultySubject: 'Physical Chemistry & Thermodynamics',
    date: 'Sep 22, 2026',
    timeSlot: '03:15 PM - 03:40 PM',
    meetingType: 'In-Person Classroom',
    roomLocation: 'Faculty Cabin 12',
    agenda: 'Attendance dip (3 lectures missed due to flu) & catch-up video lecture plan.',
    status: 'Confirmed',
    priority: 'Normal',
    parentNotes: 'Doctor certificate submitted; parent needs recorded lecture backup access.',
    facultySummary: 'Makeup doubt-clearing session scheduled with Teaching Assistant.'
  },
  {
    id: 'PTM-807',
    parentName: 'Manoj Pillai',
    parentPhone: '+91 97455-88219',
    parentEmail: 'manoj.pillai@shipping.com',
    studentName: 'Diya Pillai',
    studentRoll: 'DEL-NEET-302',
    gradeBatch: 'Grade 12 • NEET Crash & Revision',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    facultyName: 'Dr. B. R. Sen',
    facultySubject: 'Organic Chemistry & Biomolecules',
    date: 'Sep 23, 2026',
    timeSlot: '04:00 PM - 04:25 PM',
    meetingType: 'Google Meet Video',
    roomLocation: 'meet.google.com/zen-ptm-delhi',
    agenda: 'Organic mechanism reaction pathways & test anxiety counseling with Center Psychologist.',
    status: 'Requested',
    priority: 'High',
    parentNotes: 'Parent requested presence of student welfare counselor in the call.',
    facultySummary: 'Requires confidence reinforcement; scored 155/180 in mock chemistry.'
  },
  {
    id: 'PTM-808',
    parentName: 'Vikram Joshi',
    parentPhone: '+91 98200-77112',
    parentEmail: 'vikram.joshi@bankindia.co.in',
    studentName: 'Tanvi Joshi',
    studentRoll: 'MUM-CA-142',
    gradeBatch: 'CA Inter • Both Groups Intensive',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    facultyName: 'CA Hitesh Parekh',
    facultySubject: 'Corporate Law & Direct Taxes',
    date: 'Sep 23, 2026',
    timeSlot: '05:00 PM - 05:25 PM',
    meetingType: 'In-Person Classroom',
    roomLocation: 'Library Annex Cabin',
    agenda: 'Case study analysis and mock exam answers assessment.',
    status: 'Completed',
    priority: 'Normal',
    parentNotes: 'Meeting completed on Sep 18; follow-up action plan shared.',
    facultySummary: 'Action plan implemented. Homework submission updated.'
  }
];

export const MONTHLY_SIGNOFFS_DATA = [
  {
    id: 'RPT-901',
    studentName: 'Aarav Sharma',
    rollNo: 'KOTA-JEE-042',
    gradeBatch: 'Grade 12 • JEE Super-30',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 96.4,
    avgScorePercent: 88.5,
    rankInBatch: '4th / 120',
    parentName: 'Sunita Sharma (Mother)',
    parentPhone: '+91 98234-11002',
    signatureStatus: 'Digitally Signed & Approved',
    signatureHash: 'SHA256: 7e9b41a8c902ff61bc82',
    signedTimestamp: 'Sep 02, 2026 • 08:42 PM IST',
    guardianDevice: 'iOS Parent App v4.2 (FaceID Auth)',
    parentRemarks: 'Very satisfied with Physics improvement. Please keep pushing on calculus speed.',
    academicAdvisor: 'Dr. V. K. Bansal'
  },
  {
    id: 'RPT-902',
    studentName: 'Riya Mehta',
    rollNo: 'MUM-CA-108',
    gradeBatch: 'CA Foundation • Batch Alpha',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 98.2,
    avgScorePercent: 91.0,
    rankInBatch: '2nd / 85',
    parentName: 'Rajesh Mehta (Father)',
    parentPhone: '+91 98112-99834',
    signatureStatus: 'Digitally Signed & Approved',
    signatureHash: 'SHA256: 3c1a998e6d5b001a44e9',
    signedTimestamp: 'Sep 03, 2026 • 09:15 AM IST',
    guardianDevice: 'Android Parent App v4.1 (Biometric)',
    parentRemarks: 'Good consistency in accounting tests. Grateful for Saturday doubt sessions.',
    academicAdvisor: 'CA Anand Singhania'
  },
  {
    id: 'RPT-903',
    studentName: 'Kabir Deshmukh',
    rollNo: 'DEL-NEET-219',
    gradeBatch: 'Grade 11 • NEET Target AIIMS',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 94.0,
    avgScorePercent: 84.2,
    rankInBatch: '11th / 140',
    parentName: 'Dr. Anita Deshmukh (Mother)',
    parentPhone: '+91 97654-32110',
    signatureStatus: 'Digitally Signed & Approved',
    signatureHash: 'SHA256: a120ef98c41235bc0988',
    signedTimestamp: 'Sep 03, 2026 • 07:30 PM IST',
    guardianDevice: 'iOS Parent App v4.2 (FaceID Auth)',
    parentRemarks: 'Botany weak chapters are being monitored. Signed and noted teacher remarks.',
    academicAdvisor: 'Dr. Shalini Varma'
  },
  {
    id: 'RPT-904',
    studentName: 'Ananya Ramanathan',
    rollNo: 'BLR-AI-014',
    gradeBatch: 'Grade 10 • AI & Olympiad FastTrack',
    instituteCode: 'delta',
    instituteName: 'Delta Coding Academy',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 100.0,
    avgScorePercent: 97.4,
    rankInBatch: '1st / 60',
    parentName: 'Karthik Ramanathan (Father)',
    parentPhone: '+91 99441-23891',
    signatureStatus: 'Digitally Signed & Approved',
    signatureHash: 'SHA256: 88fbc10294e81a33c091',
    signedTimestamp: 'Sep 01, 2026 • 11:20 PM IST',
    guardianDevice: 'Web Parent Portal (OTP Auth)',
    parentRemarks: 'Fantastic trajectory. Preparing for the regional informatics rounds.',
    academicAdvisor: 'Prof. Arvind Nambiar'
  },
  {
    id: 'RPT-905',
    studentName: 'Varun Reddy',
    rollNo: 'HYD-CLAT-077',
    gradeBatch: 'Grade 12 • CLAT Prime',
    instituteCode: 'zenith',
    instituteName: 'Zenith Humanities & Law',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 92.5,
    avgScorePercent: 79.8,
    rankInBatch: '18th / 90',
    parentName: 'Adv. Suresh Reddy (Father)',
    parentPhone: '+91 98490-55612',
    signatureStatus: 'Pending Parent Signature',
    signatureHash: 'UNVERIFIED',
    signedTimestamp: 'Pending Signature (Grace Period: 3d left)',
    guardianDevice: 'WhatsApp Push Ping Dispatched',
    parentRemarks: 'Awaiting parent sign-off. Automated reminder dispatched.',
    academicAdvisor: 'Adv. Meenakshi Sundaram'
  },
  {
    id: 'RPT-906',
    studentName: 'Rohan Chawla',
    rollNo: 'KOTA-JEE-098',
    gradeBatch: 'Grade 11 • JEE Foundation',
    instituteCode: 'alpha',
    instituteName: 'Alpha Institute of Science & Tech',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 88.0,
    avgScorePercent: 72.1,
    rankInBatch: '45th / 120',
    parentName: 'Bhavna Chawla (Mother)',
    parentPhone: '+91 98190-44321',
    signatureStatus: 'Pending Parent Signature',
    signatureHash: 'UNVERIFIED',
    signedTimestamp: 'Pending Signature (Grace Period: 2d left)',
    guardianDevice: 'SMS & App Push Alert Sent',
    parentRemarks: 'Mother requested medical leave adjustment before signing.',
    academicAdvisor: 'Er. R. C. Mukherjee'
  },
  {
    id: 'RPT-907',
    studentName: 'Diya Pillai',
    rollNo: 'DEL-NEET-302',
    gradeBatch: 'Grade 12 • NEET Revision',
    instituteCode: 'apex',
    instituteName: 'Apex Medical Prep',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 95.0,
    avgScorePercent: 86.0,
    rankInBatch: '9th / 140',
    parentName: 'Manoj Pillai (Father)',
    parentPhone: '+91 97455-88219',
    signatureStatus: 'Disputed by Parent',
    signatureHash: 'FLAGGED_DISPUTE',
    signedTimestamp: 'Dispute Raised Sep 04, 2026',
    guardianDevice: 'Android Parent App v4.1',
    parentRemarks: 'Parent contends that Chemistry Mock Test 3 score recorded as 130 instead of 155 due to roll number barcode blur. Under regrading audit.',
    academicAdvisor: 'Dr. B. R. Sen'
  },
  {
    id: 'RPT-908',
    studentName: 'Tanvi Joshi',
    rollNo: 'MUM-CA-142',
    gradeBatch: 'CA Inter • Group 1',
    instituteCode: 'beta',
    instituteName: 'Beta Commerce Academy (CA)',
    reportMonth: 'August 2026 Academic Dossier',
    attendancePercent: 99.1,
    avgScorePercent: 89.2,
    rankInBatch: '3rd / 85',
    parentName: 'Vikram Joshi (Father)',
    parentPhone: '+91 98200-77112',
    signatureStatus: 'Digitally Signed & Approved',
    signatureHash: 'SHA256: e8011cd488921f00a912',
    signedTimestamp: 'Sep 02, 2026 • 06:10 PM IST',
    guardianDevice: 'iOS Parent App v4.2 (TouchID Auth)',
    parentRemarks: 'Appreciated teacher feedback on GST case study solving.',
    academicAdvisor: 'CA Hitesh Parekh'
  }
];

export const SIGNOFF_AUDIT_DATA = {
  meanTurnaroundDays: '1.8 Days',
  verificationYield: '100% SHA-256 Validated',
  reminderConversionRate: '91.4% Signed < 24h',
  sheetsSaved: '14,670 Sheets',
  monthlyComplianceTrend: [
    { month: 'Apr', generated: 4620, signedOnTime: 4410, delayed: 210, compliance: '95.4%' },
    { month: 'May', generated: 4710, signedOnTime: 4560, delayed: 150, compliance: '96.8%' },
    { month: 'Jun', generated: 4800, signedOnTime: 4680, delayed: 120, compliance: '97.5%' },
    { month: 'Jul', generated: 4850, signedOnTime: 4750, delayed: 100, compliance: '97.9%' },
    { month: 'Aug', generated: 4890, signedOnTime: 4802, delayed: 88, compliance: '98.2%', current: true },
    { month: 'Sep (P)', generated: 4920, signedOnTime: 4840, delayed: 80, compliance: '98.4%' }
  ],
  channelShare: [
    { channel: 'WhatsApp Cloud Push Ping', percentage: 72, openRate: '96.2%', color: 'bg-emerald-600' },
    { channel: 'Mobile App Notification (APNS/FCM)', percentage: 22, openRate: '88.4%', color: 'bg-indigo-600' },
    { channel: 'Automated SMS Fallback Gateway', percentage: 6, openRate: '82.0%', color: 'bg-amber-600' }
  ],
  campusSignoffTable: [
    { campus: 'Alpha Institute of Science & Tech', reports: 1420, signed: 1402, avgDays: '1.6d', compliance: '98.7%', status: 'Exemplary' },
    { campus: 'Beta Commerce Academy (CA)', campusCode: 'beta', reports: 980, signed: 968, avgDays: '1.8d', compliance: '98.7%', status: 'Exemplary' },
    { campus: 'Apex Medical Prep', campusCode: 'apex', reports: 1140, signed: 1118, avgDays: '2.0d', compliance: '98.0%', status: 'Optimal' },
    { campus: 'Delta Coding Academy', campusCode: 'delta', reports: 680, signed: 674, avgDays: '1.2d', compliance: '99.1%', status: 'Fast Track' },
    { campus: 'Zenith Humanities & Law', campusCode: 'zenith', reports: 670, signed: 640, avgDays: '2.4d', compliance: '95.5%', status: 'Standard' }
  ]
};

export const PARENT_GRIEVANCES_DATA = {
  totalFiled: 24,
  meanResolutionHours: '4.2 Hours',
  firstContactResolution: '87.5%',
  directorEscalations: 2,
  categoryBreakdown: [
    { category: 'Faculty Teaching Pace & Doubt Clearance', percentage: 38, count: 9, color: 'bg-indigo-600' },
    { category: 'Bus Transport & Late Pickup Notification', percentage: 25, count: 6, color: 'bg-blue-600' },
    { category: 'Fee Concession & Scholarship Calculation', percentage: 20, count: 5, color: 'bg-amber-600' },
    { category: 'Homework Load & Weekend Test Collision', percentage: 12, count: 3, color: 'bg-purple-600' },
    { category: 'OMR Scanning / Exam Re-evaluation', percentage: 5, count: 1, color: 'bg-rose-600' }
  ],
  ticketsList: [
    {
      id: 'GRV-401',
      parentName: 'Manoj Pillai',
      studentName: 'Diya Pillai (DEL-NEET-302)',
      campus: 'Apex Medical Prep',
      instituteCode: 'apex',
      category: 'OMR Scanning / Exam Re-evaluation',
      sentiment: 'Concerned',
      urgency: 'Critical',
      status: 'Under Investigation',
      filedDate: 'Sep 04, 2026',
      summary: 'Parent claims student marked 38 correct in Chemistry Section B, but score report showed 32 due to paper crease. Requesting physical OMR sheet scan.',
      directorRemarks: 'Physical OMR pulled from exam vault. Academic Dean reviewing under magnifying lens.'
    },
    {
      id: 'GRV-402',
      parentName: 'Harish Saxena',
      studentName: 'Ayush Saxena (KOTA-JEE-112)',
      campus: 'Alpha Institute of Science & Tech',
      instituteCode: 'alpha',
      category: 'Faculty Teaching Pace & Doubt Clearance',
      sentiment: 'Frustrated',
      urgency: 'High',
      status: 'Escalated to Director',
      filedDate: 'Sep 03, 2026',
      summary: 'Student unable to keep pace with Electrostatics derivations in Evening Batch. Batch has 60 students; doubts are spilling over into dinner break.',
      directorRemarks: 'Center Director scheduled 1-on-1 session with HOD Physics and assigned senior mentor.'
    },
    {
      id: 'GRV-403',
      parentName: 'Deepa Kulkarni',
      studentName: 'Omkar Kulkarni (MUM-CA-088)',
      campus: 'Beta Commerce Academy (CA)',
      instituteCode: 'beta',
      category: 'Bus Transport & Late Pickup Notification',
      sentiment: 'Neutral',
      urgency: 'Medium',
      status: 'Resolved',
      filedDate: 'Sep 02, 2026',
      summary: 'Route 4 bus GPS telemetry failed twice last week, causing 25-minute parent waiting time at Borivali stop.',
      directorRemarks: 'Fleet tracker hardware replaced; live WhatsApp GPS share link provisioned.'
    },
    {
      id: 'GRV-404',
      parentName: 'Sanjay Agarwal',
      studentName: 'Pooja Agarwal (BLR-AI-022)',
      campus: 'Delta Coding Academy',
      instituteCode: 'delta',
      category: 'Fee Concession & Scholarship Calculation',
      sentiment: 'Constructive',
      urgency: 'Medium',
      status: 'Resolved',
      filedDate: 'Sep 01, 2026',
      summary: 'National Science Olympiad 2nd round qualifier discount (15%) was not reflected in the installment ledger.',
      directorRemarks: 'Finance cashier updated student ledger; corrected receipt generated and sent to Parent App.'
    },
    {
      id: 'GRV-405',
      parentName: 'Adv. Suresh Reddy',
      studentName: 'Varun Reddy (HYD-CLAT-077)',
      campus: 'Zenith Humanities & Law',
      instituteCode: 'zenith',
      category: 'Homework Load & Weekend Test Collision',
      sentiment: 'Constructive',
      urgency: 'Low',
      status: 'Resolved',
      filedDate: 'Aug 29, 2026',
      summary: 'CLAT Mock 4 coincided with Legal Aptitude 60-page reading dossier on the same Sunday.',
      directorRemarks: 'Academic calendar staggered by 48 hours to prevent student burnout.'
    }
  ]
};
